server:
  port: 80

spring:
  thymeleaf:
    cache: false #关闭缓存

mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面url
      loginProcessingUrl: /login/form # 登录表单提交处理url
      usernameParameter: name # 对应表单中input标签中name属性的值 默认是username
      passwordParameter: pwd # 对应表单中input标签中name属性的值 默认的是password
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
      - /dist/**
      - /modules/**
      - /plugins/**
      loginType: JSON #认证后响应的类型（响应类型有:JSON/REDIRECT）